Updated Bash style as well as usage message.

diff --git a/del b/del
--- a/del
+++ b/del
@@ -1,78 +1,17 @@
 #!/bin/bash
+## **********************************************************************************
 ## 
-## CONTRIBUTORS: 
+## Name:    del
+## Author:  Gabriel Gonzalez
+## Email:   gabeg@bu.edu
+## License: The MIT License (MIT)
 ## 
-##     * Gabriel Gonzalez (gabeg@bu.edu) 
-## 
-## 
-## LICENSE: 
-## 
-##     The MIT License (MIT)
-## 
-## 
-## NAME:
-## 
-##     del - Delete files to the trash can.
-## 
-## 
-## SYNTAX: 
-## 
-##     del [-h] [--setup] [-s] [-r <file>] [<files>]
-## 
-## 
-## PURPOSE:
-## 
-##     A trash can for Linux systems so that files are not deleted forever.
-## 
-## 
-## OPTIONS:
-## 
-##     -h
-##         Print program usage.
-## 
-##     --setup
-##         Setup a new trash can location by giving a directory path.
-##     -s
-##         Print the size of the trash can.
-## 
-##     -r, --rec <file>
-##         Recovery system for deleted files.
-## 
-##     <files>
-##         Delete specified files.
-## 
-## 
-## FUNCTIONS:
-## 
-##     print_usage  - Print program usage.
-## 
-##     recover_file - Recover the specified file.
-##     delete_files - Deleted the specified files.
-## 
-## 
-## FILE STRUCTURE:
-## 
-##     * Print Program Usage
-##     * Recover and Delete Files
-##     * Trash Program Options
-## 
-## 
-## MODIFICATION HISTORY:
-## 	
-##     gabeg Sep 19 2013 <> Created.
-## 
-##     gabeg Jul 01 2014 <> Added functions to increase readability
-## 
-##     gabeg Jan 01 2015 <> Removed "print_trash_size", "backup_file_check", 
-##                          "is_file", and "is_directory". Changed "help_screen" to
-##                          "print_usage". Added the "-r" option which also enables
-##                          file recovery.
-## 
-##     gabeg Jan 14 2015 <> Added a "--setup" option so that the trash can location 
-##                          is not hardcoded, and can be modified on the fly.
-## 
-##     gabeg Apr 25 2015 <> On recovery, directories are a appended with a '/'. 
-##                          Updated input validity on recovery.
+## Syntax: del [option] <argument>
+##         
+## Description: Delete files and move them to the trash can, that way files are not
+##              deleted forever.
+##              
+## Notes: None.
 ## 
 ## **********************************************************************************
 
@@ -85,19 +24,65 @@
 ## Program information
 ARGV=("$@")
 PROG_NAME=`basename $0`
+PROG_DIR=`echo "$0" | sed "s/\/${PROG_NAME}$//"`
 
-PROG_PATH_LEN=${#0}
-PROG_NAME_LEN=${#PROG_NAME}
-PROG_DIR_LEN=$[ ${PROG_PATH_LEN} - ${PROG_NAME_LEN} - 1 ]
-
-PROG_PATH="${0:0:${PROG_DIR_LEN}}"
-
-## Array delimeter
 IFS=$'\n'
+TRASH_DIR=`head -1 "${PROG_DIR}/trash.config" | sed 's/\/$//'`
 
-## Directory locations
-TRASH_PREF="${PROG_PATH}/log/trash.pref"
-TRASH_DIR=`head -1 "${TRASH_PREF}" | sed 's/\/$//'`
+
+
+## #################################
+## ##### TRASH PROGRAM OPTIONS #####
+## #################################
+
+## Main function
+main() {
+    case "${ARGV[0]}" in
+        ""|"-h"|"--help") 
+            usage
+            exit 0
+            ;;
+        "--setup")
+            echo "Where is the trash can located?"
+            read -p "> " ans
+            
+            if [ -z "${ans}" ]; then 
+                echo "${PROG_NAME}: No path specified. Skipping trash can setup."
+                exit 0
+            fi
+            
+            if [ -d "${ans}" ]; then
+                echo "${ans}" > "${TRASH_PREF}"
+                echo 
+                echo ":: Setting new trash can location...Done."
+            else
+                echo "${PROG_NAME}: Directory '${ans}' does not exist." 1>&2
+                exit 1
+            fi
+            
+            exit 0
+            ;;
+        "-s"|"--size") 
+            size=`du -sh "${TRASH_DIR}" | cut -f1 -d'/'`
+            echo "Trash Size:" "${size}"
+            exit 0
+            ;;
+        "*~")
+            if [ ! -f "*~" ]; then
+                echo "${PROG_NAME}: No backup files found." 1>&2
+                exit 1
+            fi
+            ;;
+        "-r"|"--rec"|"--recover")
+            recover_file
+            exit 0
+            ;;
+        *) 
+            delete_files 
+            exit 0
+            ;;
+    esac
+}
 
 
 
@@ -106,9 +91,17 @@ TRASH_DIR=`head -1 "${TRASH_PREF}" | sed 's/\/$//'`
 ## ###############################
 
 ## Displays the help screen
-function print_usage {
-    echo "Usage: ${PROG_NAME} [-h] [--setup] [-s] [-r <file>] [<files>]"
-    exit 1
+usage() {
+    echo "Usage: ${PROG_NAME} [option] <argument>"
+    echo 
+    echo "Options:"
+    echo "    --setup                        Setup the trash can path"
+    echo "    -s, --size                     Display the size of the trash can"
+    echo "    -r, --rec, --recover <file>    Recover a file from the trash can"
+    echo 
+    echo "Arguments:"
+    echo "    <file>                         Input file to recover"
+    echo "    <file(s)>                      File(s) to delete"
 }
 
 
@@ -117,21 +110,80 @@ function print_usage {
 ## ##### RECOVER AND DELETE FILES #####
 ## ####################################
 
-## Recover the specified file
-function recover_file {
+## Delete the specified file(s)
+delete_files() {
+    now=`date +%b%d--%H:%M:%S`
     
-    echo ":: Recovery service"
+    ## Loop through files to delete
+    for i in "${ARGV[@]}"; do
+        if [[ "${i}" == "" ]]; then 
+            continue
+        fi
+        
+        ## File/directory check
+        if [ -f "${i}" ] || [ -d "${i}" ]; then
+            if [ -d "${i}" ]; then 
+                i=`echo "${i}" | sed -e 's/\/$//'`
+            fi
+            
+            echo -n ":: Deleting ${i}..." 
+            mv "${i}" "${TRASH_DIR}/${i}<>${now}" 
+            echo "Done"
+        else
+            echo -e "${PROG_NAME}: File '${i}' does not exist." 1>&2
+            exit 1
+        fi
+    done
+}
+
+
+
+## Recover the specified file
+recover_file() {
+    
+    ## Display matches
+    display_recovery_matches
+    read -p '> ' ans
+    
+    if [ -z "${ans}" ]; then
+        echo "${PROG_NAME}: No value specified. Skipping file recovery."
+        exit 0
+    fi
+    
+    if "$(is_valid_index "${ans}")"; then
+        echo "${PROG_NAME}: Value '${ans}' is invalid." 1>&2
+        exit 1
+    fi
+    
+    ## Recover file
+    matches=(`get_matches`)
+    names=(`echo "${matches[*]}" | cut -f1 -d'<'`)
+    i=$[ ${ans} - 1]
+    item="${names[${i}]}"
+    
+    echo 
+    echo -n ":: Transferring '${item}' to current directory..."
+    mv "${TRASH_DIR}/${matches[${i}]}" "${item}"
+    echo "Done"
+}
+
+
+
+## Display file recovery matches
+display_recovery_matches() {
     
     ## File matches
-    file="${ARGV[1]}"
-    matches=(`ls -1 -A "${TRASH_DIR}" | grep --color=never -i "${file}"`)
+    if [ -z "${ARGV[1]}" ]; then
+        echo "${PROG_NAME}: No file specified. Skipping file recovery." 
+        exit 0
+    fi
     
-    ## Number of matches
+    matches=(`get_matches`)
     n=${#matches[@]}
     last=$[ ${n} - 1 ]
     
     if [ ${n} -eq 0 ]; then
-        echo "${PROG_NAME}: No files matching '${file}' found."
+        echo "${PROG_NAME}: No files matching '${ARGV[1]}' found." 1>&2
         exit 1
     fi
     
@@ -144,131 +196,68 @@ function recover_file {
                               -e 's/Oct/Oct /' -e 's/Nov/Nov /' -e 's/Dec/Dec /' \
                         | sed 's/--/ - /'`)
     
-    ## Prompt user which file to recover
+    ## Get string padding
+    len=0
+    for i in `seq 0 ${last}`; do
+        j=$[ ${i} + 1 ]
+        item="${names[${i}]}"
+        
+        if [ ${#item} -gt ${len} ]; then len=$[ ${#item} + 3 ]; fi
+    done
+    
+    ## Display file matches
     echo "Which file would you like to recover?"
     
     for i in `seq 0 ${last}`; do
         j=$[ ${i} + 1 ]
         item="${names[${i}]}"
         
-        if [ -d "${TRASH_DIR}/${matches[${i}]}" ]; then item="${item}/"; fi
+        if [ -d "${TRASH_DIR}/${matches[${i}]}" ]; then 
+            item="${item}/"
+        fi
         
-        echo -e "${j}: ${item} \t ${times[${i}]}" \
+        printf "%s: %-${len}s %s" "${j}" "${item}" "${times[${i}]}" \
             | GREP_COLORS='mt=00;32' \
               grep --color=always -E '^.*: '
     done
-    
-    read -p '> ' ans
-    
-    ## Make sure user input was valid
+}
+
+
+
+## ###################################
+## ##### FILE RECOVERY UTILITIES #####
+## ###################################
+
+## Return files that match recovery file
+get_matches() {
+    ls -1 -A "${TRASH_DIR}" | grep --color=never -i "${ARGV[1]}"
+}
+
+
+
+## Check if match array index is valid
+is_valid_index() {
+    matches=(`get_matches`)
+    n=${#matches[@]}
     flag=false
     
-    if [ "${ans}" -eq "${ans}" ] 2> /dev/null; then 
+    if [ "$1" -eq "$1" ] 2> /dev/null; then 
         :
     else 
         flag=true
     fi
-    if "${flag}" || [[ "${ans}" == '' ]] || [ "${ans}" -le 0 -o "${ans}" -gt "${n}" ]; then
-        echo "${PROG_NAME}: Value '${ans}' is invalid."
-        exit 1
+    
+    if [ "$1" -le 0 -o "$1" -gt "${n}" ]; then
+        flag=true
     fi
     
-    ## Recover file
-    k=$[ ${ans} - 1]
-    item="${names[${k}]}"
-    
-    echo -n ":: Transferring '${item}' to current directory..."
-    mv "${TRASH_DIR}/${matches[${k}]}" "${item}"
-    echo "Done"
+    echo "${flag}"
 }
 
 
 
-## Delete the specified files
-function delete_files {
-    
-    ## Current time
-    curr=`date +%b%d--%H:%M:%S`
-    
-    ## Loop through files to delete
-    for i in "${ARGV[@]}"; do
-        
-        ## Skip over empty items
-        if [[ "${i}" == "" ]]; then continue; fi
-                
-        ## File/directory check
-        if [ -f "${i}" ] || [ -d "${i}" ]; then
-            
-            ## Remove '/' from end of directory name               
-            if [ -d "${i}" ]; then i=`echo "${i}" | sed -e 's/\/$//'`; fi
-            
-            ## Item to be deleted
-            name="${i}"
-            new="${i}<>${curr}"
-            
-            ## Move the file to the trash with new name
-            echo -n ":: Deleting ${name}..." 
-            mv "${name}" "${TRASH_DIR}/${new}" 
-            echo "Done"
-        else
-            echo -e "${PROG_NAME}: File '${i}' does not exist."
-            exit 1
-        fi
-    done
-}
-
-
-
-## #################################
-## ##### TRASH PROGRAM OPTIONS #####
-## #################################
-
-## Main function
-function main {
-    
-    ## Check user input
-    case "${ARGV[0]}" in
-        
-        ## Print Size of trash can
-        "-h") 
-            print_usage
-            ;;
-        
-        ## Setup trash can
-        "--setup")
-            echo "Where is the trash can located?"
-            read -p "> " ans
-            
-            echo "${ans}" > "${TRASH_PREF}"
-            echo -e "\n:: Setting new trash can location...Done"
-            ;;
-        
-        ## Print Size of trash can
-        "-s") 
-            size=`du -sh "${TRASH_DIR}" | cut -f1 -d'/'`
-            echo "Trash Size:" "${size}"
-            ;;
-        
-        ## Checks If There Are Backup Files
-        "*~")
-            [ ! -f "*~" ] && echo "${PROG_NAME}: No backup files found." && exit 1
-            ;;
-        
-        ## Recovers Deleted Files
-        "-r"|"--rec")
-            recover_file 
-            ;;
-        
-        ## Delete Files and If Necessary Print Syntax Error
-        *) 
-            delete_files
-            ;;
-    esac
-    
-    exit 0
-}
-
-
-
-## Execute trash program 
+## ============
+## Execute Main
+## ============
+ 
 main 
